const propertiesConstants = {
  FETCH_PROPERTIES_STARTED: 'FETCH_PROPERTIES_STARTED',
  FETCH_PROPERTIES_SUCCESS: 'FETCH_PROPERTIES_SUCCESS',
  FETCH_PROPERTIES_ERROR: 'FETCH_PROPERTIES_ERROR',
};

export default propertiesConstants;
