const propertiesConstants = {
  GET_PROPERTIES_STARTED: 'GET_PROPERTIES_STARTED',
  GET_PROPERTIES_SUCCESS: 'GET_PROPERTIES_SUCCESS',
  GET_PROPERTIES_FAILURE: 'GET_PROPERTIES_FAILURE',

  GET_PROPERTY_STARTED: 'GET_PROPERTY_STARTED',
  GET_PROPERTY_SUCCESS: 'GET_PROPERTY_SUCCESS',
  GET_PROPERTY_FAILURE: 'GET_PROPERTY_FAILURE',

  POST_PROPERTY_STARTED: 'POST_PROPERTY_STARTED',
  POST_PROPERTY_SUCCESS: 'POST_PROPERTY_SUCCESS',
  POST_PROPERTY_FAILURE: 'POST_PROPERTY_FAILURE',
};

export default propertiesConstants;
