const propertiesConstants = {
  FETCH_PROPERTIES_STARTED: 'FETCH_PROPERTIES_STARTED',
  FETCH_PROPERTIES_SUCCESS: 'FETCH_PROPERTIES_SUCCESS',
  FETCH_PROPERTIES_FAILURE: 'FETCH_PROPERTIES_FAILURE',
};

export default propertiesConstants;
